### ISSUE TITLE
Owncloud's github api url is no longer working

### ISSUE THREAD

**Issue by drybjed** [debops/ansible-owncloud#1]
Github updated their API to require the user account in the URL in addition to the repo name.

The format is now:
`https://api.github.com/repos/{{ user_account }}/{{ repo }}/keys`

https://developer.github.com/v3/repos/keys/#create

**Comment by ypid** [comment]
Does this issue (still) apply to the `debops.owncloud` role. The only usage of the GitHub’s API in the DebOps project seems to be: https://github.com/debops/ansible-rails_deploy/blob/2e1e44f0cb0cd576fe500bb305f09b16a972e550/tasks/deploy_keys.yml#L17

**Comment by ypid** [comment]
@drybjed ?

**Comment by drybjed** [comment]
No, with current `debops.owncloud` this issue is not relevant anymore since role uses APT packages instead of cloning code via `git`. Closing it.
