### ISSUE TITLE
Upgrading 8.0 -> 8.1 fails: ".htaccess file has the wrong version"

### ISSUE THREAD

**Issue by htgoebel** [debops/ansible-owncloud#17]
`.htaccess` is missing at all. But I have `.htaccess.dpkg-backup` and `.htaccess.dpkg-dist` in `/var/www/owncloud`.

**Comment by drybjed** [comment]
Is that related to https://forum.owncloud.org/viewtopic.php?f=31&t=26286 maybe? I don't think DebOps modifies `.htaccess` since `nginx` is used as frontend.

**Comment by drybjed** [comment]
There might be a solution by adding a `debconf` task which answes the question about updating the `.htaccess` file: https://debiantalk.wordpress.com/2015/03/21/owncloud-v8-to-v8-0-2-update-killing-debian-softly/

**Comment by ypid** [comment]
I did not encounter such a problem. @htgoebel Is there something we can do to debug this further or anything we should change? Otherwise can you close this for now?

**Comment by htgoebel** [comment]
Sorry, currently I have no time for trying to reproduce this again. So it it works for you, maybe it is gone.
