### ISSUE TITLE
Good defaults: PHP "output_buffering = 0"

### ISSUE THREAD

**Issue by Gomez** [debops/ansible-owncloud#18]
The ownCloud docs recommend output_buffering = 0. Right now ist output_buffering =128. 

https://doc.owncloud.org/server/8.0/admin_manual/configuration_files/big_file_upload_configuration.html#configuring-php

I can create a PR if no objection.
@scibi @ypid @drybjed

**Comment by ypid** [comment]
Good catch. You are right …
