### ISSUE TITLE
Packages and keys URL

### ISSUE THREAD

**Issue by abondis** [debops/ansible-owncloud#3]
It seems the packages and key URL pattern changes between Ubuntu and Debian for example, wouldn't that be easier/safer to just use a variable for the whole urls ?

It would be 'easy' to keep a list in the defaults based on http://software.opensuse.org/download/package?project=isv:ownCloud:community&package=owncloud but in case it changes to override it ?

**Comment by drybjed** [comment]
Sure, I agree. We can even do something like,

```
owncloud_repository_map:
  'Debian': "url1'
  'Ubuntu': 'url2'

apt_repository: repo='{{ owncloud_repository_map[ansible_distribution] }}'
```

This way it should work nicely with both distributions.

**Comment by ypid** [comment]
@abondis I only run this role against Debian GNU/Linux, however, support for Ubuntu should be straight forward now. Do you want to test with this https://github.com/debops/ansible-owncloud/pull/42 ?

**Comment by abondis** [comment]
thanks @ypid
I won't have time to test and I'm not planning on trying owncloud again for a while. Unless someone else wants to verify, I think you can close this issue.

**Comment by ypid** [comment]
Thanks for your feedback. As the test builds are running on Ubuntu, I will be working on getting the build to pass on it. Related to #42. I am closing this issue for now.
