### ISSUE TITLE
"ERROR! lookup plugin (task_src) not found"

### ISSUE THREAD

**Issue by ThibaudDauce** [debops/ansible-owncloud#32]
Hi,

I just installed Ansible 2.0.0.2 and I tried the owncloud role.
I installed it from galaxy in the folder with my other roles `ansible-galaxy install debops.owncloud -p ./roles`

When I run it, I receive this error:

```
TASK [debops.nginx : DebOps pre_tasks hook] ************************************
fatal: [xx.xx.xx.xx]: FAILED! => {"failed": true, "msg": "ERROR! lookup plugin (task_src) not found"}
```

Do you have an idea? I saw that this error was with Ansible 1.7 on Mac OSX or I'm runnig Ansible 2 on ArchLinux.

Thanks

**Comment by ypid** [comment]
https://github.com/debops/ansible-users/issues/25

**Comment by ThibaudDauce** [comment]
Thank you for the quick answer, I will look into that tomorrow!

**Comment by ypid** [comment]
Hi

I have just updated the docs today for this role. When you want to check them out, they are currently only available here: https://github.com/debops/ansible-owncloud/tree/master/docs until they will be included in the official docs. Feel free to tell us if that is helpful for you and if we can improve it.

**Comment by ThibaudDauce** [comment]
Hi,

I don't undersand where to put the file `task_src.py` in my directory structure. I don't have a `playbooks` folder to create the `lookup_plugins` folder. I only have a `roles` folder. Do you understand my problem? (I'm not sure my explanations are clear :-( )

You can add a series of steps in the getting started to run the playbook:

``` bash
ansible-galaxy install debops.owncloud -p ./roles
mkdir ???/lookup_plugins
cd ???/lookup_plugins
wget https://raw.githubusercontent.com/debops/debops-playbooks/master/playbooks/lookup_plugins/task_src.py
```

**Comment by ypid** [comment]
You will need to put the files from https://github.com/debops/debops-playbooks/tree/master/playbooks/lookup_plugins into your `lookup_plugins` as configured in your `ansible.cfg`. Please check Ansible docs for this. Your issue is not specific to this role. Some of the DebOps roles have other DebOps dependencies. This role included, you might need to checkout DebOps a bit more. https://github.com/debops/ansible-owncloud#are-you-using-this-as-a-standalone-role-without-debops. `task_src` is not used in this role.

**Comment by le9i0nx** [comment]
https://github.com/le9i0nx/ansible-root/blob/master/ansible.cfg#L7
https://github.com/le9i0nx/ansible-root
I think I made myself clear

**Comment by ypid** [comment]
@ThibaudDauce Your issue should be addressed. Can you close the issue?
