### ISSUE TITLE
Switch back to git as the installation method

### ISSUE THREAD

**Issue by drybjed** [debops/ansible-owncloud#37]
I was just made aware, that after releasing a new version of OwnCloud, the repository maintainers [removed the old .deb packages](https://download.owncloud.org/download/repositories/stable/Debian_8.0/) making this role unusable.

Sigh.

Is there any reason to use the provided `.deb` packages from upstream? Perhaps switching back to installation via `git clone` would be a better option? Not sure how would that go with upgrades.

**Comment by ypid** [comment]
Thats bad … I would suggest going with the tar balls instead. They are properly GPG signed. https://github.com/jchaney/owncloud/blob/6454579d9a0362e367abc1c10877609316c18660/Dockerfile#L42

**Comment by drybjed** [comment]
@ypid If signatures can be verified then I suppose that would be fine... And hey, it looks like you can leave old versions as tarballs.

Of course I would download them to `/usr/local/src/owncloud/` instead of `/tmp` for archival purposes.

That would also require keeping track of SHA256 checksums for `get_url` module to check integrity of downloaded files, so a set of maps that define version:checksum mapping is needed...

**Comment by ypid** [comment]
Sounds good. Then we are fully in control about updates and so on.

**Comment by ypid** [comment]
I guess we should also check if we can enable ownClouds own update mechanize to not leave people vulnerable in case of security updates.

**Comment by drybjed** [comment]
@ypid I would like to find out of the `.deb` packages were removed by accident or not, and what plans the upstream has for this. Using `.deb` packages should be a priority if possible.

Also, I need to check what changed and if the role works in the current state, since we aren't installing the `owncloud` package with specific version in mind... are we?

**Comment by ypid** [comment]
You are right. Checking the `.deb` option is first priority.

Pinning to a specific version should not be needed.

**Comment by ypid** [comment]
@drybjed You can close this issue. As of ownCloud 9.0, packages are working nicely.
