### ISSUE TITLE
Files owner problems

### ISSUE THREAD

**Issue by Polichronucci** [debops/ansible-owncloud#46]
If you try to install owncloud on a host and be ran under a different user and not www-data, then the files in the owncloud directory are not owned by the correct user and you have to change them manually from www-data to the required user. It would be nice to be able to configure the user from this role, and on initial deployment of owncloud and on an already existing installation.

**Comment by ypid** [comment]
Do you want to work on this?

Related to: https://github.com/debops/ansible-owncloud/issues/34

**Comment by ypid** [comment]
Closing in favor of #34
