### ISSUE TITLE
Documents app

### ISSUE THREAD

**Issue by Polichronucci** [debops/ansible-owncloud#52]
I am struggling with a very strange issue regarding the occ commands. I have this in my invetory

<pre>
owncloud__host_occ_cmd_list:
  - command: 'app:enable calendar'
  - command: 'app:enable contacts'
  - command: 'app:enable notes'
  - command: 'app:enable documents'
</pre>

Running the playbook will result in a successful run, running it again will result in a WARNING.

<pre>
 [WARNING]: The loop variable 'owncloud__occ_item' is already in use. You should set the `loop_var` value in the `loop_control` option for the task to something else to avoid variable collisions and unexpected behavior.
</pre>

As a result every other run the app documents is disabled and enabled respectively.

If I remove the  **\- command: 'app:enable documents'** line and the app is enabled, it gets disabled, this doesn't happen to any other apps and this is not expected to happen.

**Comment by drybjed** [comment]
@Polichronucci What happens if you put the `documents` application as first on the list? Does the `nots` enable and disable instead?

**Comment by Polichronucci** [comment]
Nope. It only effects the documents app.

**Comment by Polichronucci** [comment]
Also I didn't notice this issue before the latest commits of August 14.

**Comment by ypid** [comment]
@Polichronucci Seen [`owncloud__app_documents_enabled`](https://docs.debops.org/en/latest/ansible/roles/ansible-owncloud/docs/defaults.html#envvar-owncloud__app_documents_enabled) ? :wink:

**Comment by Polichronucci** [comment]
Yes that did the trick. Didn't even think there would be a variable dedicated to an app.
Thank you very much.
