### ISSUE TITLE
Service FQDN, domain, sender mail address

### ISSUE THREAD

**Issue by drybjed** [debops/ansible-owncloud#57]
It looks like the role uses an old scheme for things like service FQDN address (split to a subdomain and domain). I would propose these changes:

The role should keep the main domain in a string variable, not a list. I don't think that using multiple domains is useful - separate instances on different domains most likely would be installed on separate hosts anyway.

```
owncloud__domain: '{{ ansible_domain if ansible_domain else ansible_hostname }}'
```

Or better yet, hook up to `ansible_local.core.domain` for this.

The full service FQDN should be composed in a string as well, using the domain variable directly instead of adding the two together in different places.

```
owncloud__fqdn: 'cloud.{{ owncloud__domain }}'
```

This way, if a user wants to change the FQDN of the service, he doesn't need to look up a weird "subdomain"/"domain" split to know that he has to use just the first part of the address.
`
This requires a separate variable for the mail account. In the current role it's dependent on the`owncloud__subdomain`variable which is suprising when an user changes it to something different than`cloud`, and SMTP server might not accept messages sent with weird addresses like that. Since ownCloud uses separate variables for mail account name, and mail domain, let's go with that:

```
owncloud__mail_domain: '{{ owncloud__fqdn }}'
owncloud__mail_from_account: 'noreply'
```

I would change the name of the second variable from `owncloud__mail_from_address` to indicate that it's not a full e-mail address. The domain part being the equivalent of FQDN instead of the host domain makes sense to remind the user what FQDN address that service has. By default the resulting sender would be `noreply@cloud.example.com` instead of `cloud@example.com`.

This also works out well if the user decides to move the FQDN address of the service to the apex domain, with the full site address being `https://example.com/` and e-mail address being `noreply@example.com` respectively.

**Comment by ypid** [comment]
Closed by #58. Thanks to @drybjed for the review!
