### ISSUE TITLE
Enable calendar / contacts app

### ISSUE THREAD

**Issue by pulse00** [debops/ansible-owncloud#61]
```
sudo -u www-data php occ app:enable contacts

contacts not found
```

should those apps be downloaded and enabled manually?

**Comment by ypid** [comment]
> should those apps be downloaded and enabled manually?

Ideally not of course :wink: I am able to reproduce this problem in case where the `contacts` for example was not installed before (not listed in the output of `occ app:list` neither under enabled nor disabled). If the app was once enabled via the web interface, enabling and disabling works seamlessly.
Seems that ownCloud devs interpret this as the ["expected behavour"](https://github.com/owncloud/core/issues/20838#issuecomment-160660446). I reported this upstream: https://github.com/owncloud/core/issues/26166

@pulse00 Hint, as this role only installs ownCloud consider reporting issues upstream directly :wink:

**Comment by ypid** [comment]
@pulse00 Hint, the role already changes to the correct user when you run the `occ` wrapper script which the role placed in your `$PATH` for convenience :wink:

**Comment by pulse00** [comment]
@ypid thanks for the info. i still think there's something wrong with the default `debops.owncloud` installation. As far as i understand the web interface should show the `contacts` and `calendar` applications under `Not enabled` on the apps page in a default installation. 

The `debops.ownlcloud` installation shows plenty of `Not enabled` applications, but not contacts and calendar. I've tried to get some feedback in the owncloud #irc channel and they confirmed that on a fresh installation, contacts and calendar apps should be available in the web interface - though not enabled by default.

I'll try try on a fresh VM with the default owncloud installer to verify that behavior.

**Comment by ypid** [comment]
I just checked. Not sure why but in my 9.0.4 ownCloud (and other versions), not all apps are shown under "Not enabled" but instead appear under "Productivity" as not enabled. Maybe that helps? When you had an app enabled once (which installed it) and you disable it again it will be listed under "Not enabled".

**Comment by pulse00** [comment]
> appear under "Productivity" as not enabled

ok, that's embarassing :) it's there i just haven't looked unter productivity... thanks!
