### ISSUE TITLE
[security] Debian pkg OpenPGP key has changed

### ISSUE THREAD

**Issue by ypid** [debops/ansible-owncloud#65]
Ref: https://central.owncloud.org/t/owncloud-repositories-got-a-new-pgp-key/2637
Also mentioned in: https://github.com/owncloud/core/issues/23599
Fixed in: #64
Changelog: https://docs.debops.org/en/latest/ansible/roles/ansible-owncloud/docs/changelog.html#security

Please run the role against your hosts after the PR has been merged.

Old fingerprint: BCECA90325B072AB1245F739AB7C32C35180350A
New fingerprint: DDA2C105C4B73A6649AD2BBD47AE7F72479BC94B

**Comment by ypid** [comment]
Merged. Please rerun the role :wink: ~~Closing the issue in a week or so if people check here for issues.~~ Leaving it open as the keys are (still) considered weak.

Check: https://docs.debops.org/en/latest/ansible/roles/ansible-owncloud/docs/changelog.html#security

**Comment by takenek** [comment]
W: http://download.owncloud.org/download/repositories/stable/Debian_8.0/Release.gpg: Signature by key DDA2C105C4B73A6649AD2BBD47AE7F72479BC94B uses weak digest algorithm (SHA1)

I have no idea but i got still problem with new KEY.

**Comment by JohnKiller** [comment]
Same here. My `/etc/apt/sources.list.d/owncloud.list` is

`deb http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/ /`

Output of `uname -a` is

`Linux giove28 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by takenek** [comment]
Exacly and i am sure i use NEW KEY:
"Old fingerprint: BCECA90325B072AB1245F739AB7C32C35180350A
New fingerprint: DDA2C105C4B73A6649AD2BBD47AE7F72479BC94B"

And i got:
W: http://download.owncloud.org/download/repositories/stable/Debian_8.0/Release.gpg: Signature by key DDA2C105C4B73A6649AD2BBD47AE7F72479BC94B uses weak digest algorithm (SHA1)

So this is a NEW KEY.
**BUG STILL EXIST!!**

**Comment by ypid** [comment]
I only tested with Debian jessie. CI tests use Ubuntu 14.04. Please have a look at the supported distors in [meta/main.yml](https://github.com/debops/ansible-owncloud/blob/master/meta/main.yml). 

Can you submit a PR to fix this?

**Comment by takenek** [comment]
Debian Jessie don`t report about weak digest - there is no this function.
This is a new function in Debian Stretch/SiD.

Best Regards.

**Comment by ypid** [comment]
Hm, so is there any fix we can do here or does upstream need to fix this?

**Comment by takenek** [comment]
I am 100% sure this is a problem with repo.

**Comment by ypid** [comment]
ok, so seems like you should report upstream then :wink: ?

**Comment by ghost** [comment]
> I am 100% sure this is a problem with repo.

Just stumbled over this. There is no need to report this "upstream" as the repositories are correctly signed with a strong signature. However one might need to remove the sources first as it seems that ubuntu/debian is somehow caching the repository locally:

> I was able to fix it by removing the package source, followed by running apt-get update. After adding the source again, everything installed fine. Weirdly just running apt-get clean instead, which I thought does the same, did not fix my issue.

https://github.com/owncloud/client/issues/5055#issuecomment-255063655

**Comment by ypid** [comment]
@RealRancor Thanks for the hint. No offense with "reporting upstream" :wink: Sorry for that.

We could use that workaround it the role but to me this seems like a bug in Ubuntu 16.04. Any thoughts on if we should implementing that workaround? Also, [as stated above](https://github.com/debops/ansible-owncloud/issues/65#issuecomment-256296844) Ubuntu 16.04 has not been added to the list of supported distros. Any one wants to work on that or any opinions?

**Comment by takenek** [comment]
ypid: working for You on Ubuntu?
I check on Stretch and not working.

**Comment by ghost** [comment]
@ypid No offense taken, i'm also not upstream :grinning: 

Just had to point a oC user to that solution :-)

**Comment by ypid** [comment]
@RealRancor All right :wink: 

@takenek It was working when I last tried on Debian Jessie. CI tests are done with Ubuntu 14.04 and with that instillation is definitely working. Ref: https://travis-ci.org/debops/ansible-owncloud

**Comment by takenek** [comment]
ypid my mistake ofc not Jessie i talk about SiD/Stretch. ( i edit my post )
Ubuntu 14 and Debian Jessie and older releases ignore weak digest algorithm.
This problem start exist in new Distro please check on Debian Stretch and You see You get error: "weak digest algorithm"

Best Regards

**Comment by ghost** [comment]
Ok, it seems they changed something recently at the repositories to get this issue back: https://github.com/owncloud/core/issues/26500#issuecomment-256840763

So yes, there seems to be issues with the repositories again.

**Comment by ypid** [comment]
Thanks for the clarification.
