### ISSUE TITLE
Wrong php package name

### ISSUE THREAD

**Issue by nicolas-grekas** [debops/ansible-owncloud#66]
For apcu, igbinary and imagick packages, on Ubuntu 16.04, the apt package name is `php-*`, not `php7.0-*`.
Or did I miss adding some ppa source somewhere to get these names?

**Comment by ypid** [comment]
Hi

Thanks for reporting. There is no problem on your side.

This issue is already tracked upstream. I am leaving this issue open until someone fixes it upstream.

Tracked upstream: https://github.com/debops/ansible-php/issues/14
Related to: https://github.com/debops/ansible-owncloud/pull/60

**Comment by ypid** [comment]
@drybjed Fixed it upstream. Thanks! I am closing. Feel free to test and report back, either against [debops.php](https://github.com/debops/ansible-php) or against [debops.owncloud](https://github.com/debops/ansible-owncloud) as appropriate.
