### ISSUE TITLE
The mail 'From:' field contains 'DebOps Cloud' even after the site owner is changed

### ISSUE THREAD

**Issue by drybjed** [debops/ansible-owncloud#68]
I changed the default variables `owncloud__theme_title`, `owncloud__theme_name`, `owncloud__theme_entity_name`, but the e-mail messages sent by ownCloud, for example to reset the password, still contain `From: DebOps Cloud` in them. Is there a way to change this to the organization name?

**Comment by ypid** [comment]
Not quite sure why it still says `DebOps Cloud`.

Can you give me the output of:

``` shell
grep 'DebOps Cloud' /var/www/owncloud/config /var/www/owncloud/themes -R -B 10
```

**Comment by drybjed** [comment]
Sure:

```
/var/www/owncloud/themes/debops/defaults.php-    */
/var/www/owncloud/themes/debops/defaults.php-   public function getTitle() {
/var/www/owncloud/themes/debops/defaults.php-           return '<Institution name> Cloud';
/var/www/owncloud/themes/debops/defaults.php-   }
/var/www/owncloud/themes/debops/defaults.php-
/var/www/owncloud/themes/debops/defaults.php-   /**
/var/www/owncloud/themes/debops/defaults.php-    * Returns the short name of the software
/var/www/owncloud/themes/debops/defaults.php-    * @return string title
/var/www/owncloud/themes/debops/defaults.php-    */
/var/www/owncloud/themes/debops/defaults.php-   public function getName() {
/var/www/owncloud/themes/debops/defaults.php:           return 'DebOps Cloud';
/var/www/owncloud/themes/debops/defaults.php-   }
/var/www/owncloud/themes/debops/defaults.php-
/var/www/owncloud/themes/debops/defaults.php-   /**
/var/www/owncloud/themes/debops/defaults.php-    * Returns the short name of the software containing HTML strings
/var/www/owncloud/themes/debops/defaults.php-    * @return string title
/var/www/owncloud/themes/debops/defaults.php-    */
/var/www/owncloud/themes/debops/defaults.php-   public function getHTMLName() {
/var/www/owncloud/themes/debops/defaults.php:           return 'DebOps Cloud';
```

**Comment by ypid** [comment]
Have you looked at the `debops.owncloud/templates/srv/www/sites/themes/debops-template/defaults.php.j2`? How can `/var/www/owncloud/themes/debops/defaults.php` still contain 'DebOps Cloud' for `getName` when you changed `owncloud__theme_name`?

**Comment by drybjed** [comment]
False alarm. It looks like I forgot to update `owncloud__theme_name` in the inventory. After-rerunning the playbook all strings are updated.

Perhaps `owncloud__theme_name` could be the main variable and `owncloud__theme_title` could be based on it by default, similar to `owncloud__theme_name_html`? This would avoid a requirement to change the string in multiple variables.

**Comment by ypid** [comment]
Hm maybe. Although there is a reason that the two variables exist. I would like to leave it as is and rely on people changing both variables if that is what they want. Refer to the docs of both default vars.
