### ISSUE TITLE
nextcloud 13 upload limit problem

### ISSUE THREAD

**Issue by erikschwalbe** [debops/ansible-owncloud#87]
Hi, 
I installed nextcloud 13.0.2 with debops. Installation worked fine:
owncloud__variant: 'nextcloud'
owncloud__release: '13.0'
owncloud__upload_size: '20G'

Unfortunately file upload in web-ui and sync client did not work with files larger 10MB.
After a long debug session I found a solution for me. I commented out:

```
# Disallow access to hidden files and directories
location ~ /\. {
     return 404;
}
```
in /etc/nginx/sites-enabled/debops.owncloud.conf
The file upload works like aspected.

Regards,
Erik

**Comment by ypid** [comment]
@erikschwalbe Thanks for reporting. I need to check that with an Nextcloud 13. With 12, it works without issues.

Edit: I will look into this later.

**Comment by ypid** [comment]
Should be fixed by https://github.com/debops/debops/pull/470. Feel free to give feedback.
